### ISSUE TITLE
Write class to track and transform data - IEE

### ISSUE THREAD

**Issue by karol-milano** [karol-milano/CSRepo#46]
Write class to track and transform data

**Comment by renattogouvea** [comment]
- [x] Fix papers and authors insertion into the database
- [x] Define integration of wrapper with webservice
- [x] Create method for wrapper update
- [x] Check if the conference exists
- [x] Create new conference edition
- [x] Schedule 200 requests per day (IEEE API restriction)
- [ ] Create test cases for wrapper
